### ISSUE TITLE
CJuiDatePicker not working in 1.1.16

### ISSUE THREAD

**Issue by chngtrn** [yiisoft/yii#3990]
When using renderPartial with $processOutput=true, CJuiDatePicker will only work once. Subsequent ajax calls render the partial again will stopped CJuiDatePicker from working. Reverting back to 1.1.15 works perfectly.

**Comment by samdark** [comment]
Do you have time to do git bisect between 1.1.15 and 1.1.16 to find out which commit caused it?

**Comment by chngtrn** [comment]
I will do that and let you know. Thanks for responding.

**Comment by chngtrn** [comment]
Here's the problematic commit after doing the bisect.

1d4602af712ecbb49a784ba674cbe8c2e460730a is the first bad commit commit
1d4602af712ecbb49a784ba674cbe8c2e460730a Author: marcovtwout <mr@vtwout.net>
Date: Wed Nov 19 10:52:22 2014 +0100 Fixes #3636: Upgraded jQuery UI to
1.11.2 :100644 100644 6a08ac3df2506d7dc89a5f39e223d5341ac1a81a
a619786b3fa494b8ded0e7796af585dbd5ab1580 M CHANGELOG :100644 100644
9d04aefd00d91cb7e72a1131aed218522ce78777
8f8d6651ab11f77432936bbe4cb63efd952cedaa M UPGRADE :040000 040000
e51020d342c102e8162b55e8cd213322a5d230af
bf452403cffbba9bea0eac77a8bceebcbe3e1b1f M framework

**Comment by samdark** [comment]
Looks like it's the update of jQueryUI itself and not PHP code.

**Comment by chngtrn** [comment]
That seems like it is jQueryUI but it does break functionality in Yii. What can we do to fix?

**Comment by samdark** [comment]
How do you perform AJAX calls?

**Comment by chngtrn** [comment]
Just standard GET call to a controller's action.

    <?php
        echo chtml::ajaxlink($r->name,
            array('report/params', 'report_id' => $r->id),
            array(
                'type' => 'get',
                'update' => "#report-params",
            )
        );
    ?>

**Comment by samdark** [comment]
I'm not sure how to approach it. Any ideas?

**Comment by chngtrn** [comment]
I'll have to switch out the JS and try to pinpoint where it breaks.

**Comment by jjdunn** [comment]
I think we fixed this in our project after 1.1.16 upgrade, which we did in May 2015:

in CHtml::clientChange():

    if($live)
    - $cs->registerScript('Yii.CHtml.#' . $id,"jQuery('body').on('$event','#$id',function(){{$handler}});");
    - else
    -	$cs->registerScript('Yii.CHtml.#' . $id,"jQuery('#$id').on('$event', function(){{$handler}});");
    +// namespaced and unbound events first, this way ajax reloads don't result in event duplication
    if($live)
    +	$cs->registerScript('Yii.CHtml.#' . $id, "jQuery('body').off('$event.$id','#$id').on('$event.$id','#$id',function(){{$handler}});");
    + else
    + $cs->registerScript('Yii.CHtml.#' . $id, "jQuery('#$id').off('$event.$id').on('$event.$id', function(){{$handler}});");

and remember to make the same change in the Yiilite version of the code.

I don't recall exactly which of our patches fixed which problems, but I CAN tell you that we do not have the problem mentioned in this ticket, in our project:  CJuiDatePicker works just fine after an ajax-refresh of the page containing the date-picker control(s).

**Comment by samdark** [comment]
@chngtrn can you try @jjdunn patch?

**Comment by chngtrn** [comment]
Yes. I'll test it out and let you know. Thanks for the update.

**Comment by chngtrn** [comment]
I've tried @jjdunn patch and the problem is still there. Please note that I'm doing ajax update of the same DOM ID. For example, I have a DIV with id="update-form" and 5 buttons that calls the same controller action just passing different query string and all 5 buttons update the same #update-form DIV.

Any of those 5 buttons clicked the first time, the date picker would work. But if another button is clicked after the first one, date picker stopped working. This works perfectly in 1.1.15 but is the problem in 1.1.16.

I compared CHtml::clientChange in both 1.1.15 and 1.1.16  and it matches so I don't think that's where the problem is. I did the git bisect like @samdark suggested and it pointed to the jQuery code update.

**Comment by SamMousa** [comment]
@samdark Can we release 1.1.18 without this?
No one is working on this and it is not a regression from 1.1.17.

**Comment by samdark** [comment]
Either we're fixing it for this release or not fixing at all...

**Comment by SamMousa** [comment]
In that case I vote not at all ;-)
